services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${PORT:-8080}:80"  # Public entrypoint
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./scripts/health_agent.sh:/usr/local/bin/health_agent.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped
    command: >
      /bin/sh -c "
        envsubst '\$ACTIVE_POOL \$RELEASE_ID' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf &&
        nginx -g 'daemon off;' & 
        /usr/local/bin/health_agent.sh
      "
    networks:
      - bluegreen_net

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    expose:
      - "8080"
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - bluegreen_net

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    expose:
      - "8080"
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - bluegreen_net

networks:
  bluegreen_net:
    driver: bridge
