services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./scripts/health_agent.sh:/usr/local/bin/health_agent.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    depends_on:
      - app_blue
      - app_green
    command: >
      /bin/sh -c "
      chmod +x /usr/local/bin/health_agent.sh &&
      envsubst '\$ACTIVE_POOL \$RELEASE_ID' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf &&
      nginx &&
      /usr/local/bin/health_agent.sh
      "

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:8080"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:8080"
